name: Check Issue
on:
  issues:
    types:
      - opened
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install node dependencies
        run: npm install
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npm run check-issue -- --token=$GITHUB_TOKEN
