name: Issues
on:
  issues:
    types:
      - opened
      - eidted
jobs:
  label:
    runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Update Issue
    #     uses: ./.github/actions/issues
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install node dependencies
        run: npm install
      - name: Check for issues updates
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npm run update-issue -- --token=$GITHUB_TOKEN
