name: Issues
on:
  issues:
    types:
      - opened
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Issue
        uses: ./.github/actions/issues
