name: Readme
on:
  push:
    branches:
      - main
jobs:
  UpdateJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Readme
        uses: ./.github/actions/readme
